//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repositories
{
    using System;
    using System.Collections.Generic;
    
    public partial class PersonalTable
    {
        public int IDName { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Hobby { get; set; }
        public string Address { get; set; }
        public string Job { get; set; }
    }
}
